-- public.t_persons definition

-- Drop table

-- DROP TABLE public.t_persons;

CREATE TABLE public.t_persons (
                                  per_id int4 NOT NULL GENERATED BY DEFAULT AS IDENTITY,
                                  per_address varchar(255) NOT NULL,
                                  per_age int4 NOT NULL,
                                  per_dni varchar(10) NOT NULL,
                                  per_genre varchar(255) NOT NULL,
                                  per_name varchar(255) NOT NULL,
                                  per_phone varchar(255) NOT NULL,
                                  CONSTRAINT t_persons_per_age_check CHECK (((per_age <= 70) AND (per_age >= 18))),
                                  CONSTRAINT t_persons_pkey PRIMARY KEY (per_id),
                                  CONSTRAINT uk_fh2ugalpie9vwaghw34br4f7l UNIQUE (per_dni)
);


-- public.t_clients definition

-- Drop table

-- DROP TABLE public.t_clients;

CREATE TABLE public.t_clients (
                                  cli_password varchar(255) NOT NULL,
                                  cli_state bool NULL,
                                  per_id int4 NOT NULL,
                                  CONSTRAINT t_clients_pkey PRIMARY KEY (per_id),
                                  CONSTRAINT fkf2gqdav15y23k29hnrfxbu7al FOREIGN KEY (per_id) REFERENCES public.t_persons(per_id)
);


-- public.t_accounts definition

-- Drop table

-- DROP TABLE public.t_accounts;

CREATE TABLE public.t_accounts (
                                   act_id int4 NOT NULL GENERATED BY DEFAULT AS IDENTITY,
                                   act_balance numeric(19, 2) NOT NULL,
                                   act_number varchar(255) NOT NULL,
                                   act_state bool NULL,
                                   act_type varchar(255) NOT NULL,
                                   act_cli_id int4 NULL,
                                   CONSTRAINT t_accounts_act_balance_check CHECK ((act_balance >= (1)::numeric)),
                                   CONSTRAINT t_accounts_pkey PRIMARY KEY (act_id),
                                   CONSTRAINT uk_987asfgn309nb5fjymok19ug7 UNIQUE (act_number),
                                   CONSTRAINT fkrubv4pky47mvdsvmjtdtny4k1 FOREIGN KEY (act_cli_id) REFERENCES public.t_clients(per_id)
);


-- public.t_movements definition

-- Drop table

-- DROP TABLE public.t_movements;

CREATE TABLE public.t_movements (
                                    mov_id int4 NOT NULL GENERATED BY DEFAULT AS IDENTITY,
                                    mov_balance_av numeric(19, 2) NOT NULL,
                                    mov_balance_in numeric(19, 2) NOT NULL,
                                    mov_date timestamp NOT NULL,
                                    mov_type varchar(255) NOT NULL,
                                    mov_state bool NOT NULL,
                                    mov_value numeric(19, 2) NOT NULL,
                                    mov_act_id int4 NULL,
                                    CONSTRAINT t_movements_pkey PRIMARY KEY (mov_id),
                                    CONSTRAINT fk8hg9qde2yb9vd6uv7eih2t3ic FOREIGN KEY (mov_act_id) REFERENCES public.t_accounts(act_id)
);


INSERT INTO public.t_persons (per_address,per_age,per_dni,per_genre,per_name,per_phone) VALUES
    ('CREA',24,'0150749059','M','Andres Molina','0985346351');
INSERT INTO public.t_clients (cli_password,cli_state,per_id) VALUES
    ('1234',true,1);
INSERT INTO public.t_accounts (act_balance,act_number,act_state,act_type,act_cli_id) VALUES
                                                                                         (1000.00,'1',true,'AHORRO',1),
                                                                                         (1700.00,'2',true,'AHORRO',1);
INSERT INTO public.t_movements (mov_balance_av,mov_balance_in,mov_date,mov_type,mov_state,mov_value,mov_act_id) VALUES
                                                                                                                    (2600.00,2300.00,'2023-05-04','DEPOSITO',true,300.00,1),
                                                                                                                    (1800.00,2600.00,'2023-05-04','DEBITO',true,-800.00,1),
                                                                                                                    (1000.00,1800.00,'2023-05-04','DEBITO',true,-800.00,1),
                                                                                                                    (3300.00,2300.00,'2023-05-04','DEPOSITO',true,1000.00,2),
                                                                                                                    (2500.00,3300.00,'2023-05-04','DEBITO',true,-800.00,2),
                                                                                                                    (1700.00,2500.00,'2023-05-04','DEBITO',true,-800.00,2);

